Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "./shared", "/vagrant", type: "virtualbox"
  config.vm.provision :shell, path: "provisioning/bootstrap.sh"
  config.vm.network "private_network", ip: "192.168.30.2"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 1
    v.name = "varnish-1"
  end
end
